version: '2'
services:
  eurekaserver:
     container_name: eurekaService
     image:  robert0714/eurekaserver:2.1.3.RELEASE
     network_mode:  "host"
     environment:
         server.port: "8761"
         eureka.client.enabled: "true"
         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
         spring.boot.admin.url: http://localhost:8181/sba
         spring.cloud.discovery.enabled: "true"
         spring.cloud.config.server.encrypt.enabled: "false"
         TZ: Asia/Taipei
#  configserver:
#      container_name:  configService
#      image: robert0714/maas-configserver:1.0      
#      network_mode:  "host"
#      environment:
#         spring.profiles.active: "default"
#         server.port: "8888"
#         spring.cloud.config.uri: "http://localhost:8888"  
#         ENCRYPT_KEY:       "IMSYMMETRIC"
#         eureka.client.enabled: "true"
#         eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
#         spring.boot.admin.url: http://localhost:8181/sba
#         spring.cloud.discovery.enabled: "true"
#         spring.cloud.config.server.encrypt.enabled: "false"
#         spring.cloud.config.server.git.uri:  https://github.com/robert0714/maas-config-repo/
#         spring.cloud.config.server.git.searchPaths:  authentication-service
#         ENCRYPT_KEY:       "IMSYMMETRIC"
#         TZ: Asia/Taipei
#      depends_on:
#           - "eurekaserver"  
  zipkin:
    image: openzipkin/zipkin
    container_name:  zipkin
#    ports:
#      - "9411:9411"
    network_mode:  "host"
    environment: 
      spring.profiles.active: "default"
      server.port: "9411" 
      spring.cloud.config.uri: "http://localhost:8888" 
      eureka.client.enabled: "true"
      eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
      spring.boot.admin.url: http://localhost:8181/sba
      TZ: Asia/Taipei
      STORAGE_TYPE: mem   
  sba2:      
      image: robert0714/spring-boot-admin-server-2:2.1.3
      container_name: sba2
      network_mode:  "host"
      environment:
        spring.profiles.active: "secure"
        server.port: "8182" 
        spring.cloud.config.uri: "http://localhost:8888" 
        eureka.client.enabled: "true"
        eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
#        spring.boot.admin.url: http://localhost:8182/sba2       
#        spring.boot.admin.context-path: /sba2
        TZ: Asia/Taipei
      depends_on:
        - "eurekaserver"     