
#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false 
                   
#Setting logging levels
logging:
  file:
    mylog.log
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    develop.ptx: DEBUG
    
server:
  port: 8010
